[versions]
google-ksp = "2.3.6"
kotlin = "2.3.10"
agp = "8.13.2"
kotlinpoet = "2.2.0"
androidx-lifecycle = "2.9.6"
ktor = "3.4.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
google-ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "google-ksp" }
squareup-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
squareup-kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
